/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  await knex("games_table").del();
  await knex("games_table").insert([
    {
      id: 1,
      title: "Red, Blue, Green",
      platform: "Game Boy",
      release_date: 19960227,
      generation: 1,
    },
    {
      id: 2,
      title: "Yellow",
      platform: "Game Boy",
      release_date: 19980912,
      generation: 1,
    },
    {
      id: 3,
      title: "Gold, Silver",
      platform: "Game Boy Color",
      release_date: 19991121,
      generation: 2,
    },
    {
      id: 4,
      title: "Crystal",
      platform: "Game Boy Color",
      release_date: 20001214,
      generation: 2,
    },
    {
      id: 5,
      title: "Ruby, Sapphire",
      platform: "Game Boy Advance",
      release_date: 20021121,
      generation: 3,
    },
    {
      id: 6,
      title: "FireRed, LeafGreen",
      platform: "Game Boy Advance",
      release_date: 20040129,
      generation: 3,
    },
    {
      id: 7,
      title: "Emerald",
      platform: "Game Boy Advance",
      release_date: 20040916,
      generation: 3,
    },
    {
      id: 8,
      title: "Diamond, Pearl",
      platform: "Nintendo DS",
      release_date: 20060928,
      generation: 4,
    },
    {
      id: 9,
      title: "Platinum",
      platform: "Nintendo DS",
      release_date: 20080913,
      generation: 4,
    },
    {
      id: 10,
      title: "HeartGold, SoulSilver",
      platform: "Nintendo DS",
      release_date: 20090912,
      generation: 4,
    },
    {
      id: 11,
      title: "Black, White",
      platform: "Nintendo DS",
      release_date: 20100918,
      generation: 5,
    },
    {
      id: 12,
      title: "Black2, White2",
      platform: "Nintendo DS",
      release_date: 20120623,
      generation: 5,
    },
    {
      id: 13,
      title: "X, Y",
      platform: "Nintendo 3DS",
      release_date: 20131012,
      generation: 6,
    },
    {
      id: 14,
      title: "OmegaRuby, AlphaSapphire",
      platform: "Nintendo 3DS",
      release_date: 20141121,
      generation: 6,
    },
    {
      id: 15,
      title: "Sun, Moon",
      platform: "Nintendo 3DS",
      release_date: 20161118,
      generation: 7,
    },
    {
      id: 16,
      title: "UltraSun, Ultra Moon",
      platform: "Nintendo 3DS",
      release_date: 20161118,
      generation: 7,
    },
    {
      id: 17,
      title: "Let's go Pikachu!, Let's go Eevee!",
      platform: "Nintendo Switch",
      release_date: 20161118,
      generation: 7,
    },
    {
      id: 18,
      title: "Sword, Shield",
      platform: "Nintendo Switch",
      release_date: 20191115,
      generation: 8,
    },
    {
      id: 19,
      title: "Brilliant Diamond, Shining Pearl",
      platform: "Nintendo Switch",
      release_date: 20211119,
      generation: 8,
    },
    {
      id: 20,
      title: "Legends: Arceus",
      platform: "Nintendo Switch",
      release_date: 20220128,
      generation: 8,
    },
    {
      id: 21,
      title: "Scarlet, Violet",
      platform: "Nintendo Switch",
      release_date: 20221118,
      generation: 9,
    },
  ]);
};
